"""initial schema

Revision ID: 52002a23bee4
Revises: 
Create Date: 2026-10-07 01:30:26.416676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52002a23bee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('monopolies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('monopoly_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_table('court_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monopoly_id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('court_name', sa.String(length=200), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('decision_link', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['monopoly_id'], ['monopolies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monopoly_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monopoly_id'], ['monopolies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monopoly_id', 'year')
    )
    op.create_table('period_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'metric_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period_values')
    op.drop_table('periods')
    op.drop_table('court_cases')
    op.drop_table('monopolies')
    op.drop_table('metrics')
    op.drop_table('industries')
    # ### end Alembic commands ###
